# Generated by Django 5.2.1 on 2025-05-31 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_services', '0002_user_email_verification_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
